project:
  type: book
  output-dir: docs

book:
  title: "Statistical Thinking"
  subtitle: ETC2420/5242
  # author: "Minh Huynh"
  # date: "10/29/2025"
  downloads: pdf
  reader-mode: true
  sidebar:
    align: left
    style: floating
    collapse-level: 3
    pinned: true
    
  chapters:
    - index.qmd
    - 1_Questions.qmd
    - 2_Probability.qmd
    - 3_MeasurementError.qmd
    - 4_Estimation.qmd
    - 5_HypothesisTesting.qmd
    - 6_SimulationBasedInference.qmd
    - 7_Likelihood.qmd
    - 8_Bayes.qmd
    - 9_bayes2.qmd
    - 10_Models1.qmd
    
bibliography: references.bib

format:
  html:
    self-contained: false
    css: 
      - styles.css
      - include/webex.css
    include-after-body: 
      - include/webex.js
    theme:
      light: 
        - flatly
        #- custom.scss
      dark: 
        - darkly
        #- custom.scss
    number-sections: true
  pdf: default

editor: visual

