project:
  type: book
  output-dir: docs

book:
  title: "Statistical Thinking"
  subtitle: ETC2420/5242
  # author: "Minh Huynh"
  # date: "10/29/2025"
  downloads: pdf
  reader-mode: true
  sidebar:
    align: left
    style: floating
    collapse-level: 2
    pinned: false
    
  chapters:
    - index.qmd
    - Questions.qmd
    - Probability.qmd
    - apples.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    self-contained: false
    css: 
      - styles.css
      - include/webex.css
    include-after-body: 
      - include/webex.js
    theme:
      light: 
        - flatly
        #- custom.scss
      dark: 
        - darkly
        #- custom.scss
    number-sections: true
  pdf: default

editor: visual

